name: 'Deploy using VPN and SSH'
description: 'Connects to a server via OpenVPN (or not; depends on the passed variables), connects via SSH and copies / runs scripts to / on the target'
inputs:
  key:
    description: 'The private key to use when connecting via SSH.'
    required: true
  key-name:
    description: 'Name of the file the private key is temporarily saved in. Defaults to `identity`.'
    required: true
    default: 'identity'
runs:
  using: "composite"
  steps:
    - name: Setup SSH - make dir .ssh
      shell: bash
      run: sudo mkdir .ssh
    - name: Setup SSH - set .ssh permissions
      shell: bash
      run: sudo chmod 700 .ssh
    - name: Setup SSH - touch .ssh/${{ inputs.key-name }}
      shell: bash
      run: sudo touch .ssh/${{ inputs.key-name }}
    - name: Setup SSH - fill .ssh/${{ inputs.key-name }}
      shell: bash
      run: sudo echo "${{ inputs.key }}" >> .ssh/${{ inputs.key-name }}
    - name: Setup SSH - chmod .ssh/${{ inputs.key-name }}
      shell: bash
      run: sudo chmod 600 .ssh/${{ inputs.key-name }}