name: 'Create SSH private-key from secret'
description: 'Takes an input and persists it in the .ssh dir (creates it first; sets permissions) as a private key using the given filename to use later.'
inputs:
  key:
    description: 'The private key to use when connecting via SSH.'
    required: true
  key-name:
    description: 'Name of the file the private key is temporarily saved in. Defaults to `identity`.'
    required: true
    default: 'identity'
runs:
  using: "composite"
  steps:
    - name: Setup SSH - make dir .ssh
      shell: bash
      run: sudo mkdir .ssh
    - name: Setup SSH - touch .ssh/${{ inputs.key-name }}
      shell: bash
      run: sudo touch .ssh/${{ inputs.key-name }}
    - name: Setup SSH - fill .ssh/${{ inputs.key-name }}
      shell: bash
      run: sudo echo "${{ inputs.key }}" | sudo tee -a .ssh/${{ inputs.key-name }} > /dev/null
    - name: Setup SSH - chmod .ssh/${{ inputs.key-name }}
      shell: bash
      run: sudo chmod 600 .ssh/${{ inputs.key-name }}